In [1]:
import numpy as np
print(np.__version__)

2.3.1


In [2]:
l1 = [1,2,3,4,5]
l2 = [[1,2,3],[4,5,6]]
l3 = [[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]],[[100,200,300],[400,500,600]]]

In [3]:
l3

[[[1, 2, 3], [4, 5, 6]],
 [[10, 20, 30], [40, 50, 60]],
 [[100, 200, 300], [400, 500, 600]]]

In [11]:
n1 = np.array(l1)
n2 = np.array(l2)
n3 = np.array(l3)

In [12]:
print(n1,type(n1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [13]:
# numpy mei hum number of elements change nhi kr skte hai bss yhi diff hai
# numpy aur list mei  aur numpy fast hoti hai list ke comparision mei

In [14]:
l3[0][1][2]

6

In [15]:
n3[0][1][2]

np.int64(6)

In [16]:
n3[0,1,2]

np.int64(6)

In [10]:
n1.shape

(5,)

In [18]:
n2.shape

(2, 3)

In [19]:
n3.shape

(3, 2, 3)

In [20]:
# shape basically hame dimension batata hai 
# ndim , it basically tells num of dimensions i have

In [21]:
n3.ndim

3

In [22]:
# negative indexing is also allowed
n3[-1,1,-1]

np.int64(600)

In [23]:
# dtype means numpy ka datatype
n3.dtype

dtype('int64')

In [24]:
n3 = np.array(l3,dtype='float32')

In [25]:
n3

array([[[  1.,   2.,   3.],
        [  4.,   5.,   6.]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.]],

       [[100., 200., 300.],
        [400., 500., 600.]]], dtype=float32)

In [30]:
n3 = np.array(l3,dtype='f8')
n3,n3.dtype

(array([[[  1.,   2.,   3.],
         [  4.,   5.,   6.]],
 
        [[ 10.,  20.,  30.],
         [ 40.,  50.,  60.]],
 
        [[100., 200., 300.],
         [400., 500., 600.]]]),
 dtype('float64'))

In [29]:
n3[0,1,2]

np.float64(6.0)

In [32]:
print(n3[0],type(n3[0,0,0]))

[[1. 2. 3.]
 [4. 5. 6.]] <class 'numpy.float64'>


In [2]:
l = [[1,2,3],[4,5]]
a = np.array(l)
a

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [36]:
l = [[1,2,3],[4,5,6]]
a = np.array(l)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# numpy mei homogenous values jati hai aur zig zag nhi ho skti


In [38]:
l = [[1,2,3],[4,5]]
a = np.array(l,dtype='O')
a

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [39]:
# more creation methods: arange, linspace, ones, zeros, eye, diag

In [48]:
n1 = np.arange(1,101,4,dtype='f4')
# start stop and step

In [49]:
n1

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41., 45., 49.,
       53., 57., 61., 65., 69., 73., 77., 81., 85., 89., 93., 97.],
      dtype=float32)

In [50]:
# linspace 
# starting value stop thrid one is no. of argument

In [53]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [55]:
# ones
shape = [2,3,3]
np.ones(shape)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [56]:
shape = [2,3]
np.ones(shape)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
# zeros
shape = [2,3,3]
np.zeros(shape)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [58]:
# eye
# it basically gives an identity matrix

In [59]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
# diag
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [65]:
# numpy random module
np.random.rand(2,3)

array([[0.31369612, 0.034076  , 0.77501426],
       [0.97615035, 0.6756106 , 0.67999341]])

In [67]:
np.random.random(size=(2,3))
# both are same bss syntax mei diff hai bss

array([[0.92207883, 0.49237005, 0.38585596],
       [0.70433116, 0.17868389, 0.18532896]])

In [74]:
np.random.randn(2,3)
# iski range -infinity to + infinity

array([[ 1.03336113, -0.3695513 ,  1.7168424 ],
       [ 1.04890372, -0.18090016,  0.56949941]])

In [75]:
np.random.randint(10,20,size=(2,3))

array([[11, 13, 10],
       [18, 10, 12]], dtype=int32)

In [11]:
np.random.choice(np.arange(10,21),size=(3,2),p=[0.5,0.1,0,0,0,0.2,0.2,0,0,0,0])

array([[11, 10],
       [16, 15],
       [10, 15]])

In [12]:
# yha p mei jo array hai vo ek probablity parameter hai jiske hum 
# yeh decide  krte hai ki  konsa element sbse jyada aayega

In [14]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
np.random.seed(1)
np.random.shuffle(a)
a

array([12, 13, 14, 19, 11, 16, 10, 17, 20, 18, 15])

In [18]:
# /Fixes random output
np.random.seed(1)
a

array([12, 13, 14, 19, 11, 16, 10, 17, 20, 18, 15])

In [19]:
np.random.seed(1)
a

array([12, 13, 14, 19, 11, 16, 10, 17, 20, 18, 15])

In [25]:
a  = np.arange(10,22)

In [26]:
a.shape

(12,)

In [27]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [28]:
b = a.reshape((2,-1,2))


In [29]:
b

array([[[10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21]]])

In [30]:
b.reshape(-1)
# 1d mei convert kr dena

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [31]:
a = np.arange(100).reshape(10,10)

In [32]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
a[2:7,3:7]
# a[row_start:row_end, column_start:column_end]


array([[23, 24, 25, 26],
       [33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66]])

In [34]:
a[5:8,::-1]

array([[59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70]])

In [36]:
b = a[3:7]

In [37]:
b

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [38]:
b[0] = np.arange(1000,1010)

In [39]:
b

array([[1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69]])

In [40]:
a

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [41]:
np.shares_memory(a,b)
# is used to check whether two NumPy arrays share the same memory 
# (i.e., whether they view the same data in memory).

True

In [42]:
c = a[3:7].copy()

In [43]:
c

array([[1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69]])

In [45]:
c[0] = np.arange(100,110)

In [46]:
c

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69]])

In [47]:
a

array([[ 100,  101,  102,  103,  104,  105,  106,  107,  108,  109],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [48]:
np.shares_memory(a,c)

False

In [49]:
a[3:6,2:4] = np.arange(200,206).reshape((3,2))

In [50]:
a

array([[ 100,  101,  102,  103,  104,  105,  106,  107,  108,  109],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1000, 1001,  200,  201, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,  202,  203,   44,   45,   46,   47,   48,   49],
       [  50,   51,  204,  205,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [60]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
# /operators
a+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
a-5


array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [63]:
a*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [64]:
a/5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [65]:
a//5

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2])

In [66]:
a%5

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0])

In [67]:
a**5

array([     0,      1,     32,    243,   1024,   3125,   7776,  16807,
        32768,  59049, 100000])

In [68]:
a>=5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [69]:
a+=5

In [70]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
a = np.arange(10)
b = np.arange(10,20)
c = np.arange(20,40)

In [73]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [79]:
a+c
# a mei 10 the aur c mei 20 that'why we can't add it

ValueError: operands could not be broadcast together with shapes (10,) (20,) 

In [80]:
a/b

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [81]:
a<=b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [82]:
a+b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [83]:
a = np.arange(0,10).reshape((5,2))
b = np.arange(0,10).reshape((5,2))

In [84]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [85]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [86]:
a+b

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [87]:
np.logical_and(a,b)

array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [88]:
(a>=b) | (b>5)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [101]:
np.add(a,b)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [106]:
np.subtract(a,b)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [108]:
c = np.multiply(a,b)

In [109]:
c

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [110]:
np.divide(a,b)

C:\Users\Asus\AppData\Local\Temp\ipykernel_3324\2626738034.py:1: RuntimeWarning: invalid value encountered in divide
  np.divide(a,b)


array([[nan,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [111]:
np.divmod(a,b)

C:\Users\Asus\AppData\Local\Temp\ipykernel_3324\3434828917.py:1: RuntimeWarning: divide by zero encountered in divmod
  np.divmod(a,b)


(array([[0, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]),
 array([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]))

In [112]:
# first array is quotients and second array is remender

In [113]:
x = np.array([1,2,3,4,5,6,7])
m = 2
c = 3
y = m*x+c
print(y)

[ 5  7  9 11 13 15 17]


In [114]:
a = np.arange(10,20)
b = np.arange(10,21)

In [115]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [117]:
a[[0,3,9,9]]

array([10, 13, 19, 19])

In [118]:
a = np.arange(100).reshape((10,10))

In [119]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [120]:
a[[6,3,8,2]]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [122]:
a[[6,5,2,8],[0,2,4,6]]
# here 1st mei row and second mei col hai

array([60, 52, 24, 86])

In [123]:

a[:,[5,3,8,7]]

array([[ 5,  3,  8,  7],
       [15, 13, 18, 17],
       [25, 23, 28, 27],
       [35, 33, 38, 37],
       [45, 43, 48, 47],
       [55, 53, 58, 57],
       [65, 63, 68, 67],
       [75, 73, 78, 77],
       [85, 83, 88, 87],
       [95, 93, 98, 97]])

In [135]:
a[[6,3,8,2]][:,[2,4,7,9]]

array([[62, 64, 67, 69],
       [32, 34, 37, 39],
       [82, 84, 87, 89],
       [22, 24, 27, 29]])

In [141]:
a

array([10, 23, 31, 40, 50])

In [137]:
a = np.array([10,23,31,40,50])

In [138]:
a

array([10, 23, 31, 40, 50])

In [139]:
a[[True,False,True,True,False]]

array([10, 31, 40])

In [140]:
a

array([10, 23, 31, 40, 50])

In [144]:
a = np.arange(100).reshape(10,10)

In [145]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [148]:
a[[True,False,True,False,True,False,False,True,True,False]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [149]:
# hame minimum utne to dalne hi hai jitne 

In [151]:
a[:,[True,False,True,False,False,True,False,True,False,False]]

array([[ 0,  2,  5,  7],
       [10, 12, 15, 17],
       [20, 22, 25, 27],
       [30, 32, 35, 37],
       [40, 42, 45, 47],
       [50, 52, 55, 57],
       [60, 62, 65, 67],
       [70, 72, 75, 77],
       [80, 82, 85, 87],
       [90, 92, 95, 97]])

In [152]:
a[a%3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [153]:
a[a[:,0]%4 == 0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [154]:
a[a%4 == 0]

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [157]:
a[:,a[0] % 4 == 0]

array([[ 0,  4,  8],
       [10, 14, 18],
       [20, 24, 28],
       [30, 34, 38],
       [40, 44, 48],
       [50, 54, 58],
       [60, 64, 68],
       [70, 74, 78],
       [80, 84, 88],
       [90, 94, 98]])

In [158]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [159]:
a = np.arange(60).reshape((12,5))

In [160]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [161]:
# axis = 0 means mean of column
# asix = 1 means mean of row
np.mean(a,axis = 1)

array([ 2.,  7., 12., 17., 22., 27., 32., 37., 42., 47., 52., 57.])

In [162]:
np.sum(a,axis = 1)

array([ 10,  35,  60,  85, 110, 135, 160, 185, 210, 235, 260, 285])

In [163]:
np.max(a)

np.int64(59)

In [164]:
a = np.array([1,2,3])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [165]:
a+b

array([[11, 22, 33],
       [41, 52, 63],
       [71, 82, 93]])

In [166]:
a = np.array([[1],[2],[3]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [167]:
a

array([[1],
       [2],
       [3]])

In [168]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [170]:
np.argmax(a)
# Index of the maximum value in array a

np.int64(2)

In [172]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [173]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [174]:
# (1×5 + 2×7) = 5 + 14 = 19

# (1×6 + 2×8) = 6 + 16 = 22

# → First row of result = [19, 22]

# Step 2: Second row of a with columns of b:
# (3×5 + 4×7) = 15 + 28 = 43

# (3×6 + 4×8) = 18 + 32 = 50

# → Second row of result = [43, 50]

In [176]:
a@b
# same as a.dot(b)

array([[19, 22],
       [43, 50]])

In [177]:
arr = np.array([[1,2],[-3,4],[5,6]])
arr

array([[ 1,  2],
       [-3,  4],
       [ 5,  6]])

In [180]:
arr[arr[:,0] >= 0]

array([[1, 2],
       [5, 6]])