In [1]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.3.0'

In [4]:
np.__version__

'2.3.1'

In [5]:
l1 = [10,20,30,40,50]
# Series

In [8]:
pds = pd.Series(l1)

In [9]:
pds

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
type(pds)

pandas.core.series.Series

In [11]:
pds[2]

np.int64(30)

In [17]:
pds = pd.Series(l1,index=['A','B','C','D','E'],dtype='f8')

In [18]:
pds

A    10.0
B    20.0
C    30.0
D    40.0
E    50.0
dtype: float64

In [19]:
pds['C']

np.float64(30.0)

In [20]:
pds.iloc[3]
# iloc se bhi access kr skte hai ise baad mei delhte hai 

np.float64(40.0)

In [22]:
# Dataframe
marks = {
    'DBMS': [25,27,0,22,23],
    'OS': [26,28,11,23,19],
    'CN': [13,25,26,30,24]
}

In [23]:
marks

{'DBMS': [25, 27, 0, 22, 23],
 'OS': [26, 28, 11, 23, 19],
 'CN': [13, 25, 26, 30, 24]}

In [50]:
df = pd.DataFrame(marks,index=['A','B','C','D','E'])

In [51]:
df

DBMS  OS  CN
A    25  26  13
B    27  28  25
C     0  11  26
D    22  23  30
E    23  19  24

In [33]:
df = pd.DataFrame(marks,index=['A','B','C','D','E'],columns=['DBMS','CN'])

In [34]:
df

DBMS  CN
A    25  13
B    27  25
C     0  26
D    22  30
E    23  24

In [36]:
# aur hame sabhi mei marks same hi dene honge sabhi col mei same
# count of element hi hone chahihye

In [40]:
na = np.random.randint(50,100,(10,3))
# isme marks 50 to 100 ke bich mei honge aur 10*3 ka matrix hai

In [41]:
na

array([[67, 99, 78],
       [57, 52, 96],
       [57, 56, 92],
       [83, 98, 78],
       [62, 67, 56],
       [85, 62, 56],
       [70, 70, 63],
       [65, 74, 55],
       [99, 92, 64],
       [55, 83, 72]], dtype=int32)

In [43]:
df2 = pd.DataFrame(na)

In [44]:
df2

0   1   2
0  67  99  78
1  57  52  96
2  57  56  92
3  83  98  78
4  62  67  56
5  85  62  56
6  70  70  63
7  65  74  55
8  99  92  64
9  55  83  72

In [46]:
df2 = pd.DataFrame(na,columns = ['DBMS','OS','CN'])

In [47]:
df2

DBMS  OS  CN
0    67  99  78
1    57  52  96
2    57  56  92
3    83  98  78
4    62  67  56
5    85  62  56
6    70  70  63
7    65  74  55
8    99  92  64
9    55  83  72

In [52]:
df.shape

(5, 3)

In [53]:
df

DBMS  OS  CN
A    25  26  13
B    27  28  25
C     0  11  26
D    22  23  30
E    23  19  24

In [57]:
df2.head()
# yeh by default 5 top ki values print krta hai

DBMS  OS  CN
0    67  99  78
1    57  52  96
2    57  56  92
3    83  98  78
4    62  67  56

In [58]:
df2.head(7)

DBMS  OS  CN
0    67  99  78
1    57  52  96
2    57  56  92
3    83  98  78
4    62  67  56
5    85  62  56
6    70  70  63

In [60]:
df2.head(2)

DBMS  OS  CN
0    67  99  78
1    57  52  96

In [62]:
df2 = pd.DataFrame(na,columns = ['DBMS','OS','CN'],index=[i for i in range(1,11)])

In [63]:
df2

DBMS  OS  CN
1     67  99  78
2     57  52  96
3     57  56  92
4     83  98  78
5     62  67  56
6     85  62  56
7     70  70  63
8     65  74  55
9     99  92  64
10    55  83  72

In [64]:
df2.tail(3)

DBMS  OS  CN
8     65  74  55
9     99  92  64
10    55  83  72

In [65]:
df2.tail()

DBMS  OS  CN
6     85  62  56
7     70  70  63
8     65  74  55
9     99  92  64
10    55  83  72

In [67]:
df2.head(-4)
# negative value niche se 4 ele ko hata degi

DBMS  OS  CN
1    67  99  78
2    57  52  96
3    57  56  92
4    83  98  78
5    62  67  56
6    85  62  56

In [69]:
df2.values
# it gives me a numpy array

array([[67, 99, 78],
       [57, 52, 96],
       [57, 56, 92],
       [83, 98, 78],
       [62, 67, 56],
       [85, 62, 56],
       [70, 70, 63],
       [65, 74, 55],
       [99, 92, 64],
       [55, 83, 72]], dtype=int32)

In [70]:
df.columns

Index(['DBMS', 'OS', 'CN'], dtype='object')

In [71]:
df

DBMS  OS  CN
A    25  26  13
B    27  28  25
C     0  11  26
D    22  23  30
E    23  19  24

In [72]:
df2

DBMS  OS  CN
1     67  99  78
2     57  52  96
3     57  56  92
4     83  98  78
5     62  67  56
6     85  62  56
7     70  70  63
8     65  74  55
9     99  92  64
10    55  83  72

In [76]:
df.to_csv("Marks.csv",sep='|')

In [78]:
ndf = pd.read_csv("Marks.csv",sep='|', index_col='Unnamed: 0')

In [79]:
ndf

DBMS  OS  CN
A    25  26  13
B    27  28  25
C     0  11  26
D    22  23  30
E    23  19  24

In [81]:
df.to_csv("Marks.csv",sep='|',index = False)

In [83]:
ndf = pd.read_csv("Marks.csv",sep='|')
ndf

DBMS  OS  CN
0    25  26  13
1    27  28  25
2     0  11  26
3    22  23  30
4    23  19  24

In [84]:
df.to_csv("Marks.csv",sep='|')

In [85]:
ndf = pd.read_csv("Marks.csv",sep='|')
ndf

Unnamed: 0  DBMS  OS  CN
0          A    25  26  13
1          B    27  28  25
2          C     0  11  26
3          D    22  23  30
4          E    23  19  24

In [86]:
df2.describe()

DBMS         OS         CN
count  10.000000  10.000000  10.000000
mean   70.000000  75.300000  71.000000
std    14.514361  17.016659  14.847372
min    55.000000  52.000000  55.000000
25%    58.250000  63.250000  57.750000
50%    66.000000  72.000000  68.000000
75%    79.750000  89.750000  78.000000
max    99.000000  99.000000  96.000000

In [87]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 1 to 10
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DBMS    10 non-null     int32
 1   OS      10 non-null     int32
 2   CN      10 non-null     int32
dtypes: int32(3)
memory usage: 200.0 bytes


In [91]:
df.drop(columns=['OS','CN'])
# yeh same dataframe mei drop nhi krta hai
# same mei krne ke liye inplace ka use krna hota hai

DBMS
A    25
B    27
C     0
D    22
E    23

In [92]:
df.drop(index=['A','C'])

DBMS  OS  CN
B    27  28  25
D    22  23  30
E    23  19  24

In [93]:
df['CN']

A    13
B    25
C    26
D    30
E    24
Name: CN, dtype: int64

In [95]:
df[['OS','CN']]
# jis order mei naam dete hai usi order mei aa jate hai

OS  CN
A  26  13
B  28  25
C  11  26
D  23  30
E  19  24

In [96]:
df.iloc[3]

DBMS    22
OS      23
CN      30
Name: D, dtype: int64

In [97]:
df

DBMS  OS  CN
A    25  26  13
B    27  28  25
C     0  11  26
D    22  23  30
E    23  19  24

In [98]:
df.iloc[3,2]

np.int64(30)

In [102]:
df.iloc[[3,1,4,2]]

DBMS  OS  CN
D    22  23  30
B    27  28  25
E    23  19  24
C     0  11  26

In [104]:
df.iloc[[0,2,4],[0,2]]

DBMS  CN
A    25  13
C     0  26
E    23  24

In [105]:
df.iloc[::2,::2]

DBMS  CN
A    25  13
C     0  26
E    23  24

In [107]:
df.loc[['A','C','E'],['OS','CN']]
# location hai yeh

OS  CN
A  26  13
C  11  26
E  19  24

In [109]:
df.loc['A':'E':2]

DBMS  OS  CN
A    25  26  13
C     0  11  26
E    23  19  24

In [110]:
df.iloc[[True,False,False,True,True]]

DBMS  OS  CN
A    25  26  13
D    22  23  30
E    23  19  24

In [113]:
df[df['DBMS'] >= 20]

DBMS  OS  CN
A    25  26  13
B    27  28  25
D    22  23  30
E    23  19  24

In [114]:
df[(df['DBMS'] >= 20) & (df['CN'] >= 20)]

DBMS  OS  CN
B    27  28  25
D    22  23  30
E    23  19  24

In [115]:
ndf = df[df['DBMS'] >= 20]
ndf = ndf[ndf['CN'] >= 20]
ndf

DBMS  OS  CN
B    27  28  25
D    22  23  30
E    23  19  24

In [116]:
df2

DBMS  OS  CN
1     67  99  78
2     57  52  96
3     57  56  92
4     83  98  78
5     62  67  56
6     85  62  56
7     70  70  63
8     65  74  55
9     99  92  64
10    55  83  72

In [117]:
df2['DBMS'].unique()

array([67, 57, 83, 62, 85, 70, 65, 99, 55], dtype=int32)

In [118]:
df2.value_counts()

DBMS  OS  CN
55    83  72    1
57    52  96    1
      56  92    1
62    67  56    1
65    74  55    1
67    99  78    1
70    70  63    1
83    98  78    1
85    62  56    1
99    92  64    1
Name: count, dtype: int64

In [119]:
df2['DBMS'].value_counts()

DBMS
57    2
67    1
83    1
62    1
85    1
70    1
65    1
99    1
55    1
Name: count, dtype: int64

In [123]:
a = np.array([1,3,2,1,4,2,4,5,6,7,6])
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7])

In [124]:
np.unique(a,return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7]), array([2, 2, 1, 2, 1, 2, 1]))

In [127]:
df.sort_values(by='DBMS',ascending=False)
# yha ek naya daaframe aa rha hai agar original dataframe mei 
# change krna hai to hame  inplace = true dena hoga

DBMS  OS  CN
B    27  28  25
A    25  26  13
E    23  19  24
D    22  23  30
C     0  11  26

In [130]:
df.sort_values(by= 'A',axis = 1)
# yha a wale column ke basis par sort kr ddiya hai

CN  DBMS  OS
A  13    25  26
B  25    27  28
C  26     0  11
D  30    22  23
E  24    23  19

In [131]:
pds = pd.Series(['A','B','C','B','A','B'])

In [132]:
pds

0    A
1    B
2    C
3    B
4    A
5    B
dtype: object

In [135]:
pdd = pd.get_dummies(pds,dtype='i1')
# here i1 is a datatype int8

In [136]:
pdd

A  B  C
0  1  0  0
1  0  1  0
2  0  0  1
3  0  1  0
4  1  0  0
5  0  1  0

In [137]:
data = pd.read_csv("weather_data_cities.csv")

In [138]:
data

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [141]:
data['temperature'].mean()

np.float64(56.166666666666664)

In [144]:
data[data['city'] == 'new york']['temperature'].mean()

np.float64(32.25)

In [146]:
gdf = data.groupby(by = 'city')

In [147]:
for city,group in gdf:
    print(city)
    print(group)
    print()

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny

paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy



In [148]:
gdf['temperature'].mean()

city
mumbai      88.50
new york    32.25
paris       47.75
Name: temperature, dtype: float64

In [149]:
gdf = data.groupby(by = 'event')

In [150]:
for event,group in gdf:
    print(event)
    print(group)
    print()

Cloudy
         day   city  temperature  windspeed   event
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

Fog
        day    city  temperature  windspeed event
5  1/2/2017  mumbai           85         12   Fog
6  1/3/2017  mumbai           87         15   Fog

Rain
        day      city  temperature  windspeed event
0  1/1/2017  new york           32          6  Rain
7  1/4/2017    mumbai           92          5  Rain

Snow
        day      city  temperature  windspeed event
2  1/3/2017  new york           28         12  Snow

Sunny
        day      city  temperature  windspeed  event
1  1/2/2017  new york           36          7  Sunny
3  1/4/2017  new york           33          7  Sunny
4  1/1/2017    mumbai           90          5  Sunny
8  1/1/2017     paris           45         20  Sunny



In [152]:
gdf['windspeed'].mean()

event
Cloudy    10.333333
Fog       13.500000
Rain       5.500000
Snow      12.000000
Sunny      9.750000
Name: windspeed, dtype: float64

In [154]:
data.pivot(columns = 'city', index='day')
# pivot ka use rearrange your entire table 
# here coloum is city and day is row

temperature                windspeed                 event           \
city          mumbai new york paris    mumbai new york paris mumbai new york   
day                                                                            
1/1/2017          90       32    45         5        6    20  Sunny     Rain   
1/2/2017          85       36    50        12        7    13    Fog    Sunny   
1/3/2017          87       28    54        15       12     8    Fog     Snow   
1/4/2017          92       33    42         5        7    10   Rain    Sunny   

                  
city       paris  
day               
1/1/2017   Sunny  
1/2/2017  Cloudy  
1/3/2017  Cloudy  
1/4/2017  Cloudy

In [155]:
d1 = {
    'A' : [10,20,30,40],
    'B' : [3,4,5,6]
}
d2 = {
    'A' : [30,40,50,60],
    'C' : [3,4,5,6]
}

In [156]:
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

In [157]:
df1

A  B
0  10  3
1  20  4
2  30  5
3  40  6

## 

In [158]:
df2

A  C
0  30  3
1  40  4
2  50  5
3  60  6

In [160]:
df3 = pd.concat([df1,df2])
df3
# yeh by default row  wise add krta hai

A    B    C
0  10  3.0  NaN
1  20  4.0  NaN
2  30  5.0  NaN
3  40  6.0  NaN
0  30  NaN  3.0
1  40  NaN  4.0
2  50  NaN  5.0
3  60  NaN  6.0

In [163]:
df3 = pd.concat([df1,df2],axis = 1)
df3
# yeh column wise add kr diya

A  B   A  C
0  10  3  30  3
1  20  4  40  4
2  30  5  50  5
3  40  6  60  6

In [164]:
df3 = pd.concat([df1,df2],join='inner')
df3

A
0  10
1  20
2  30
3  40
0  30
1  40
2  50
3  60

In [165]:
df3 = pd.concat([df1,df2],join='outer')
df3

A    B    C
0  10  3.0  NaN
1  20  4.0  NaN
2  30  5.0  NaN
3  40  6.0  NaN
0  30  NaN  3.0
1  40  NaN  4.0
2  50  NaN  5.0
3  60  NaN  6.0

In [168]:
df1

A  B
0  10  3
1  20  4
2  30  5
3  40  6

In [169]:
df2

A  C
0  30  3
1  40  4
2  50  5
3  60  6

In [167]:
df3 = pd.merge(df1,df2,how='inner')
df3

A  B  C
0  30  5  3
1  40  6  4

In [170]:
df3 = pd.merge(df1,df2,how='outer')
df3

A    B    C
0  10  3.0  NaN
1  20  4.0  NaN
2  30  5.0  3.0
3  40  6.0  4.0
4  50  NaN  5.0
5  60  NaN  6.0

In [171]:
df3 = pd.merge(df1,df2,how='right')
df3

A    B  C
0  30  5.0  3
1  40  6.0  4
2  50  NaN  5
3  60  NaN  6

In [172]:
df3 = pd.merge(df1,df2,how='left')
df3

A  B    C
0  10  3  NaN
1  20  4  NaN
2  30  5  3.0
3  40  6  4.0

In [173]:
# agar col ke naam diff hai to on lga skte hai left on and right on

In [176]:

df3

A  B    C
0  10  3  NaN
1  20  4  NaN
2  30  5  3.0
3  40  6  4.0

In [179]:
df3.dropna()
# drop nan

A  B    C
2  30  5  3.0
3  40  6  4.0

In [180]:
df3.fillna(df3.mean())

A  B    C
0  10  3  3.5
1  20  4  3.5
2  30  5  3.0
3  40  6  4.0