In [212]:
import pandas as pd
import numpy as np

In [213]:
pd.__version__

'2.3.0'

In [214]:
np.__version__

'2.3.1'

In [215]:
l1 = [10,20,30,40,50]
# Series

In [216]:
pds = pd.Series(l1)

In [217]:
pds

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [218]:
type(pds)

pandas.core.series.Series

In [219]:
pds[2]

np.int64(30)

In [220]:
pds = pd.Series(l1,index=['A','B','C','D','E'],dtype='f8')

In [221]:
pds

A    10.0
B    20.0
C    30.0
D    40.0
E    50.0
dtype: float64

In [222]:
pds['C']

np.float64(30.0)

In [223]:
pds.iloc[3]
# iloc se bhi access kr skte hai ise baad mei delhte hai 

np.float64(40.0)

In [224]:
# Dataframe
marks = {
    'DBMS': [25,27,0,22,23],
    'OS': [26,28,11,23,19],
    'CN': [13,25,26,30,24]
}

In [225]:
marks

{'DBMS': [25, 27, 0, 22, 23],
 'OS': [26, 28, 11, 23, 19],
 'CN': [13, 25, 26, 30, 24]}

In [226]:
df = pd.DataFrame(marks,index=['A','B','C','D','E'])

In [227]:
df

DBMS  OS  CN
A    25  26  13
B    27  28  25
C     0  11  26
D    22  23  30
E    23  19  24

In [228]:
df = pd.DataFrame(marks,index=['A','B','C','D','E'],columns=['DBMS','CN'])

In [229]:
df

DBMS  CN
A    25  13
B    27  25
C     0  26
D    22  30
E    23  24

In [230]:
# aur hame sabhi mei marks same hi dene honge sabhi col mei same
# count of element hi hone chahihye

In [231]:
na = np.random.randint(50,100,(10,3))
# isme marks 50 to 100 ke bich mei honge aur 10*3 ka matrix hai

In [232]:
na

array([[52, 93, 76],
       [73, 95, 60],
       [85, 88, 97],
       [98, 80, 73],
       [97, 71, 99],
       [63, 94, 92],
       [52, 66, 82],
       [97, 58, 95],
       [54, 59, 56],
       [52, 79, 54]], dtype=int32)

In [233]:
df2 = pd.DataFrame(na)

In [234]:
df2

0   1   2
0  52  93  76
1  73  95  60
2  85  88  97
3  98  80  73
4  97  71  99
5  63  94  92
6  52  66  82
7  97  58  95
8  54  59  56
9  52  79  54

In [235]:
df2 = pd.DataFrame(na,columns = ['DBMS','OS','CN'])

In [236]:
df2

DBMS  OS  CN
0    52  93  76
1    73  95  60
2    85  88  97
3    98  80  73
4    97  71  99
5    63  94  92
6    52  66  82
7    97  58  95
8    54  59  56
9    52  79  54

In [237]:
df.shape

(5, 2)

In [238]:
df

DBMS  CN
A    25  13
B    27  25
C     0  26
D    22  30
E    23  24

In [239]:
df2.head()
# yeh by default 5 top ki values print krta hai

DBMS  OS  CN
0    52  93  76
1    73  95  60
2    85  88  97
3    98  80  73
4    97  71  99

In [240]:
df2.head(7)

DBMS  OS  CN
0    52  93  76
1    73  95  60
2    85  88  97
3    98  80  73
4    97  71  99
5    63  94  92
6    52  66  82

In [241]:
df2.head(2)

DBMS  OS  CN
0    52  93  76
1    73  95  60

In [242]:
df2 = pd.DataFrame(na,columns = ['DBMS','OS','CN'],index=[i for i in range(1,11)])

In [243]:
df2

DBMS  OS  CN
1     52  93  76
2     73  95  60
3     85  88  97
4     98  80  73
5     97  71  99
6     63  94  92
7     52  66  82
8     97  58  95
9     54  59  56
10    52  79  54

In [244]:
df2.tail(3)

DBMS  OS  CN
8     97  58  95
9     54  59  56
10    52  79  54

In [245]:
df2.tail()

DBMS  OS  CN
6     63  94  92
7     52  66  82
8     97  58  95
9     54  59  56
10    52  79  54

In [246]:
df2.head(-4)
# negative value niche se 4 ele ko hata degi

DBMS  OS  CN
1    52  93  76
2    73  95  60
3    85  88  97
4    98  80  73
5    97  71  99
6    63  94  92

In [247]:
df2.values
# it gives me a numpy array

array([[52, 93, 76],
       [73, 95, 60],
       [85, 88, 97],
       [98, 80, 73],
       [97, 71, 99],
       [63, 94, 92],
       [52, 66, 82],
       [97, 58, 95],
       [54, 59, 56],
       [52, 79, 54]], dtype=int32)

In [248]:
df.columns

Index(['DBMS', 'CN'], dtype='object')

In [249]:
df

DBMS  CN
A    25  13
B    27  25
C     0  26
D    22  30
E    23  24

In [250]:
df2

DBMS  OS  CN
1     52  93  76
2     73  95  60
3     85  88  97
4     98  80  73
5     97  71  99
6     63  94  92
7     52  66  82
8     97  58  95
9     54  59  56
10    52  79  54

In [251]:
df.to_csv("Marks.csv",sep='|')

In [252]:
ndf = pd.read_csv("Marks.csv",sep='|', index_col='Unnamed: 0')

In [253]:
ndf

DBMS  CN
A    25  13
B    27  25
C     0  26
D    22  30
E    23  24

In [254]:
df.to_csv("Marks.csv",sep='|',index = False)

In [255]:
ndf = pd.read_csv("Marks.csv",sep='|')
ndf

DBMS  CN
0    25  13
1    27  25
2     0  26
3    22  30
4    23  24

In [256]:
df.to_csv("Marks.csv",sep='|')

In [257]:
ndf = pd.read_csv("Marks.csv",sep='|')
ndf

Unnamed: 0  DBMS  CN
0          A    25  13
1          B    27  25
2          C     0  26
3          D    22  30
4          E    23  24

In [258]:
df2.describe()

DBMS         OS         CN
count  10.000000  10.000000  10.000000
mean   72.300000  78.300000  78.400000
std    20.276149  14.252095  17.366635
min    52.000000  58.000000  54.000000
25%    52.500000  67.250000  63.250000
50%    68.000000  79.500000  79.000000
75%    94.000000  91.750000  94.250000
max    98.000000  95.000000  99.000000

In [259]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 1 to 10
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DBMS    10 non-null     int32
 1   OS      10 non-null     int32
 2   CN      10 non-null     int32
dtypes: int32(3)
memory usage: 200.0 bytes


In [261]:
print(df.columns)


Index(['DBMS', 'CN'], dtype='object')


In [262]:
df2.drop(columns=['OS','CN'])
# yeh same dataframe mei drop nhi krta hai
# same mei krne ke liye inplace ka use krna hota hai

DBMS
1     52
2     73
3     85
4     98
5     97
6     63
7     52
8     97
9     54
10    52

In [ ]:
df.drop(index=['A','C'])

In [ ]:
df['CN']

In [ ]:
df[['OS','CN']]
# jis order mei naam dete hai usi order mei aa jate hai

In [ ]:
df.iloc[3]

In [157]:
df

DBMS  CN
A    25  13
B    27  25
C     0  26
D    22  30
E    23  24

In [263]:
df2.iloc[3,2]

np.int32(73)

In [159]:
df.iloc[[3,1,4,2]]

DBMS  CN
D    22  30
B    27  25
E    23  24
C     0  26

In [264]:
df2.iloc[[0,2,4],[0,2]]

DBMS  CN
1    52  76
3    85  97
5    97  99

In [161]:
df.iloc[::2,::2]

DBMS
A    25
C     0
E    23

In [269]:
print(df.index)


Index(['A', 'B', 'C', 'D', 'E'], dtype='object')


In [270]:
df.loc[['A','C','E'],['DBMS','CN']]
# location hai yeh

DBMS  CN
A    25  13
C     0  26
E    23  24

In [163]:
df.loc['A':'E':2]

DBMS  CN
A    25  13
C     0  26
E    23  24

In [164]:
df.iloc[[True,False,False,True,True]]

DBMS  CN
A    25  13
D    22  30
E    23  24

In [165]:
df[df['DBMS'] >= 20]

DBMS  CN
A    25  13
B    27  25
D    22  30
E    23  24

In [166]:
df[(df['DBMS'] >= 20) & (df['CN'] >= 20)]

DBMS  CN
B    27  25
D    22  30
E    23  24

In [167]:
ndf = df[df['DBMS'] >= 20]
ndf = ndf[ndf['CN'] >= 20]
ndf

DBMS  CN
B    27  25
D    22  30
E    23  24

In [168]:
df2

DBMS  OS  CN
1     68  59  52
2     91  75  82
3     78  77  90
4     59  63  77
5     65  72  68
6     56  82  82
7     60  63  66
8     92  68  74
9     54  70  89
10    62  87  61

In [169]:
df2['DBMS'].unique()

array([68, 91, 78, 59, 65, 56, 60, 92, 54, 62], dtype=int32)

In [170]:
df2.value_counts()

DBMS  OS  CN
54    70  89    1
56    82  82    1
59    63  77    1
60    63  66    1
62    87  61    1
65    72  68    1
68    59  52    1
78    77  90    1
91    75  82    1
92    68  74    1
Name: count, dtype: int64

In [171]:
df2['DBMS'].value_counts()

DBMS
68    1
91    1
78    1
59    1
65    1
56    1
60    1
92    1
54    1
62    1
Name: count, dtype: int64

In [172]:
a = np.array([1,3,2,1,4,2,4,5,6,7,6])
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7])

In [173]:
np.unique(a,return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7]), array([2, 2, 1, 2, 1, 2, 1]))

In [174]:
df.sort_values(by='DBMS',ascending=False)
# yha ek naya daaframe aa rha hai agar original dataframe mei 
# change krna hai to hame  inplace = true dena hoga

DBMS  CN
B    27  25
A    25  13
E    23  24
D    22  30
C     0  26

In [175]:
df.sort_values(by= 'A',axis = 1)
# yha a wale column ke basis par sort kr ddiya hai

CN  DBMS
A  13    25
B  25    27
C  26     0
D  30    22
E  24    23

In [176]:
pds = pd.Series(['A','B','C','B','A','B'])

In [177]:
pds

0    A
1    B
2    C
3    B
4    A
5    B
dtype: object

In [178]:
pdd = pd.get_dummies(pds,dtype='i1')
# here i1 is a datatype int8

In [179]:
pdd

A  B  C
0  1  0  0
1  0  1  0
2  0  0  1
3  0  1  0
4  1  0  0
5  0  1  0

In [180]:
data = pd.read_csv("weather_data_cities.csv")

In [181]:
data

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [182]:
data['temperature'].mean()

np.float64(56.166666666666664)

In [183]:
data[data['city'] == 'new york']['temperature'].mean()

np.float64(32.25)

In [184]:
gdf = data.groupby(by = 'city')

In [185]:
for city,group in gdf:
    print(city)
    print(group)
    print()

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny

paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy



In [186]:
gdf['temperature'].mean()

city
mumbai      88.50
new york    32.25
paris       47.75
Name: temperature, dtype: float64

In [187]:
gdf = data.groupby(by = 'event')

In [188]:
for event,group in gdf:
    print(event)
    print(group)
    print()

Cloudy
         day   city  temperature  windspeed   event
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

Fog
        day    city  temperature  windspeed event
5  1/2/2017  mumbai           85         12   Fog
6  1/3/2017  mumbai           87         15   Fog

Rain
        day      city  temperature  windspeed event
0  1/1/2017  new york           32          6  Rain
7  1/4/2017    mumbai           92          5  Rain

Snow
        day      city  temperature  windspeed event
2  1/3/2017  new york           28         12  Snow

Sunny
        day      city  temperature  windspeed  event
1  1/2/2017  new york           36          7  Sunny
3  1/4/2017  new york           33          7  Sunny
4  1/1/2017    mumbai           90          5  Sunny
8  1/1/2017     paris           45         20  Sunny



In [189]:
gdf['windspeed'].mean()

event
Cloudy    10.333333
Fog       13.500000
Rain       5.500000
Snow      12.000000
Sunny      9.750000
Name: windspeed, dtype: float64

In [190]:
data.pivot(columns = 'city', index='day')
# pivot ka use rearrange your entire table 
# here coloum is city and day is row

temperature                windspeed                 event           \
city          mumbai new york paris    mumbai new york paris mumbai new york   
day                                                                            
1/1/2017          90       32    45         5        6    20  Sunny     Rain   
1/2/2017          85       36    50        12        7    13    Fog    Sunny   
1/3/2017          87       28    54        15       12     8    Fog     Snow   
1/4/2017          92       33    42         5        7    10   Rain    Sunny   

                  
city       paris  
day               
1/1/2017   Sunny  
1/2/2017  Cloudy  
1/3/2017  Cloudy  
1/4/2017  Cloudy

In [191]:
d1 = {
    'A' : [10,20,30,40],
    'B' : [3,4,5,6]
}
d2 = {
    'A' : [30,40,50,60],
    'C' : [3,4,5,6]
}

In [192]:
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

In [193]:
df1

A  B
0  10  3
1  20  4
2  30  5
3  40  6

## 

In [194]:
df2

A  C
0  30  3
1  40  4
2  50  5
3  60  6

In [195]:
df3 = pd.concat([df1,df2])
df3
# yeh by default row  wise add krta hai

A    B    C
0  10  3.0  NaN
1  20  4.0  NaN
2  30  5.0  NaN
3  40  6.0  NaN
0  30  NaN  3.0
1  40  NaN  4.0
2  50  NaN  5.0
3  60  NaN  6.0

In [196]:
df3 = pd.concat([df1,df2],axis = 1)
df3
# yeh column wise add kr diya

A  B   A  C
0  10  3  30  3
1  20  4  40  4
2  30  5  50  5
3  40  6  60  6

In [197]:
df3 = pd.concat([df1,df2],join='inner')
df3

A
0  10
1  20
2  30
3  40
0  30
1  40
2  50
3  60

In [198]:
df3 = pd.concat([df1,df2],join='outer')
df3

A    B    C
0  10  3.0  NaN
1  20  4.0  NaN
2  30  5.0  NaN
3  40  6.0  NaN
0  30  NaN  3.0
1  40  NaN  4.0
2  50  NaN  5.0
3  60  NaN  6.0

In [199]:
df1

A  B
0  10  3
1  20  4
2  30  5
3  40  6

In [200]:
df2

A  C
0  30  3
1  40  4
2  50  5
3  60  6

In [201]:
df3 = pd.merge(df1,df2,how='inner')
df3

A  B  C
0  30  5  3
1  40  6  4

In [202]:
df3 = pd.merge(df1,df2,how='outer')
df3

A    B    C
0  10  3.0  NaN
1  20  4.0  NaN
2  30  5.0  3.0
3  40  6.0  4.0
4  50  NaN  5.0
5  60  NaN  6.0

In [203]:
df3 = pd.merge(df1,df2,how='right')
df3

A    B  C
0  30  5.0  3
1  40  6.0  4
2  50  NaN  5
3  60  NaN  6

In [204]:
df3 = pd.merge(df1,df2,how='left')
df3

A  B    C
0  10  3  NaN
1  20  4  NaN
2  30  5  3.0
3  40  6  4.0

In [205]:
# agar col ke naam diff hai to on lga skte hai left on and right on

In [206]:

df3

A  B    C
0  10  3  NaN
1  20  4  NaN
2  30  5  3.0
3  40  6  4.0

In [207]:
df3.dropna()
# drop nan

A  B    C
2  30  5  3.0
3  40  6  4.0

In [208]:
df3.fillna(df3.mean())

A  B    C
0  10  3  3.5
1  20  4  3.5
2  30  5  3.0
3  40  6  4.0

In [209]:
df3.interpolate('linear',limit_direction='both')
# Ye missing values ko linear interpolation method se fill karta hai.

# Matlab: Agar kisi column mein 2 known values ke beech mein NaN hai, to Pandas unka average trend dekh ke beech ke values ko estimate karega.

A  B    C
0  10  3  3.0
1  20  4  3.0
2  30  5  3.0
3  40  6  4.0