In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
y = np.array([4,5,6,7,8])


In [3]:
def add(x,y):
    return x+y

In [5]:
myfun = np.frompyfunc(add,2,1)
# here 2 is input func and 1 is output fun
print(myfun(x,y))

[5 7 9 11 13]


In [6]:
print(type(np.add))


<class 'numpy.ufunc'>


In [7]:
print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>


In [8]:
print(type(np.niiomom))

AttributeError: module 'numpy' has no attribute 'niiomom'

In [9]:
base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


In [10]:
arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [11]:

x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [12]:
arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [13]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)


[ 90. 180. 270. 360.]
